---
- name: rhel | 7 -> Register
  when: ansible_distribution_major_version|int == 7
  redhat_subscription: state=present username="{{ lookup('file', '~/rhn_username') }}" password="{{ lookup('file', '~/rhn_password') }}" autosubscribe=true

- name: rhel | 7 -> Enable Extra Repo
  when: ansible_distribution_major_version|int == 7
  command: "subscription-manager repos --enable rhel-7-server-extras-rpms"
