---
- name: iptables | Enable at boot
  service: name=iptables enabled=yes state=started

- name: iptables | Get rules
  command: iptables -L --wait
  register: iptablesrules
  always_run: yes
  changed_when: false

- name: iptables | Open etcd client port
  command: /sbin/iptables -I KUBECLUSTER 1 -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "etcd_{{ item }}"
  when: iptablesrules.stdout.find('etcd_{{ item }}') == -1
  notify:
    - save iptables rules
  with_items:
    - "{{ etcd_client_port }}"
    - "{{ etcd_peer_port }}"
