---
- name: restart kubelet
  command: /bin/true
  notify:
    - check kubelet existence
    - restart kubelet service
  when: inventory_hostname in groups['nodes']

- name: check kubelet existence
  command: "kubelet --version=true"  
  register: has_kubelet
  failed_when: false
  changed_when: false

- name: restart kubelet service
  service: name=kubelet state=restarted
  when: has_kubelet.rc|int != 2

- name: restart proxy
  service: name=kube-proxy state=restarted
  when: inventory_hostname in groups['nodes']

- name: restart apiserver
  service: name=kube-apiserver state=restarted
  when: inventory_hostname in groups['masters']

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted
  when: inventory_hostname in groups['masters']

- name: restart scheduler
  service: name=kube-scheduler state=restarted
  when: inventory_hostname in groups['masters']

- name: restart kube-addons
  service: name=kube-addons state=restarted
  when: inventory_hostname in groups['masters']
