---
- name: restart kubelet
  service: name=kubelet state=restarted
  when: inventory_hostname in groups['nodes']

- name: restart proxy
  service: name=kube-proxy state=restarted
  when: inventory_hostname in groups['nodes']

- name: restart apiserver
  service: name=kube-apiserver state=restarted
  when: inventory_hostname in groups['masters']

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted
  when: inventory_hostname in groups['masters']

- name: restart scheduler
  service: name=kube-scheduler state=restarted
  when: inventory_hostname in groups['masters']

- name: restart kube-addons
  service: name=kube-addons state=restarted
  when: inventory_hostname in groups['masters']
