---
- name: iptables | Enable at boot
  service: name=iptables enabled=yes state=started

- name: iptables | Get rules
  command: iptables -L --wait
  register: iptablesrules
  always_run: yes
  changed_when: false

- name: iptables | Open apiserver port
  command: /sbin/iptables -I KUBECLUSTER 1 -p tcp --dport {{ kube_master_api_port }} -j ACCEPT -m comment --comment "kube-apiserver"
  when: iptablesrules.stdout.find('kube-apiserver') == -1
  notify:
    - save iptables rules
