---
# This playbook deploys a kubernetes cluster 
# with the default addons.

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

- name: Install etcd
  hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

- name: Install flannel
  hosts:
    - etcd
    - masters
    - nodes
  sudo: yes
  roles:
    - flannel
  tags:
    - flannel

- name: Install kube master services
  hosts: masters
  sudo: yes
  roles:
    - master
  tags:
    - masters

- name: Launch addons, like dns
  hosts: masters
  sudo: yes
  roles:
    - kubernetes-addons
  tags:
    - addons
    - dns

- name: Install kube node services
  hosts: nodes
  sudo: yes
  roles:
    - node
  tags:
    - nodes
