---
- name: kluster-logging | Assures {{ kube_addons_dir }}/cluster-logging dir exists
  file: path={{ kube_addons_dir }}/cluster-logging state=directory

- name: kluster-logging | Download files from Kubernetes repo
  get_url:
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/fluentd-elasticsearch/{{ item }}
    dest="{{ kube_addons_dir }}/cluster-logging/"
    force=yes
  with_items:
    - es-controller.yaml
    - es-service.yaml
    - kibana-controller.yaml
    - kibana-service.yaml
