---
- name: debian | Init temp facts
  set_fact:
    s: false

- name: debian | Install PyYAML
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: python-yaml
    state: latest
  register: s

- name: debian | Say we install package
  set_fact:
    package_installed: true
  when: s.rc == 0
